### ISSUE TITLE
Special characters are output as question marks

### ISSUE THREAD

**Issue by HMBM47** [OrfeasZ/ZHMTools#1]
Examples:
"Fran?ois Rouzier"
should be 
"François Rouzier"

"J?r?me Quirion"
should be
"Jérôme Quirion"

The are names of NPCs in 006D465C6F70C066.TEMP in chunk27patch1.rpkg.

NVM. I see that the RPKG Tool reads the files the same way since I suspect they ARE question marks. 
I would suppose that value is just there for identification? Interesting.

**Comment by OrfeasZ** [comment]
They are indeed encoded with question marks. I assume that the names displayed on the UI are fetched from elsewhere (maybe REPO?). If you look at the raw data of that TEMP file (with a  hex editor for example), you'll see that `ç` is encoded as `0x3F`, which is the question mark symbol:

![](https://i.nofate.me/lA08DaYenw04aWZi.png)
