### ISSUE TITLE
TEMP conversion access violation

### ISSUE THREAD

**Issue by atampy25** [OrfeasZ/ZHMTools#19]
Running `HM3 convert TEMP 005A8EE337CA2012.TEMP 005A8EE337CA2012.TEMP.json` outputs nothing, causes an access violation and creates a blank file. [The TEMP file in question](https://cdn.discordapp.com/attachments/876703845303062529/1069912840623882310/005A8EE337CA2012.TEMP) is a chunk7patch1 file.

```
Faulting application name: ResourceTool.exe, version: 0.0.0.0, time stamp: 0x63d2febb
Faulting module name: ResourceLib_HM3.dll, version: 0.0.0.0, time stamp: 0x63d2fe6e
Exception code: 0xc0000005
Fault offset: 0x00000000000c9585
Faulting process ID: 0x87c0
Faulting application start time: 0x01d93556a26a541d
Faulting application path: ResourceTool.exe
Faulting module path: ResourceLib_HM3.dll
```

There is a [file with the same hash and filesize](https://cdn.discordapp.com/attachments/876703845303062529/1069913246481514506/005A8EE337CA2012.TEMP) (but slightly different content from what I can tell) in chunk2patch3; that file converts fine, producing [this JSON](https://cdn.discordapp.com/attachments/876703845303062529/1069913246871588956/005A8EE337CA2012.TEMP.json).

**Comment by OrfeasZ** [comment]
The `S25DProjectionSettings` structure changed in the latest update, causing this file to fail to deserialize. Not much I can do about that unfortunately.
