### ISSUE TITLE
.TEMP not being converted back correctly?

### ISSUE THREAD

**Issue by HMBM47** [OrfeasZ/ZHMTools#2]
Not sure what's causing this issue exactly, but if you convert to .json and right back to .TEMP, Chongqing's 
0005C60C0B3C7977.TEMP [assembly:/_pro/scenes/missions/wet/scenario_rat.brick].pc_entitytype 
from chunk6patch1.rpkg,
it results in everyone evacuating the underground facility.

**Comment by HMBM47** [comment]
I thought for sure the program was the issue, but turns out I didn't thoroughly troubleshoot enough. 
It was my fault! (Where exactly, I dunno) Carry on...

**Comment by HMBM47** [comment]
It's happening again. Know for certain I'm using the raw files.
For whatever reason, the last two loads it was fine, but further tests broke it again.

**Comment by hitman-resources** [comment]
This issue (or similar) also breaks garage doors, causing them to display the Open prompt even when already open and preventing them from being closed.

[Video of garage door bug](https://cdn.discordapp.com/attachments/882827151345324073/882828758644572160/cBM6gLpeRR.mp4)

**Comment by Notexe** [comment]
> 
> 
> This issue (or similar) also breaks garage doors, causing them to display the Open prompt even when already open and preventing them from being closed.
> 
> [Video of garage door bug](https://cdn.discordapp.com/attachments/882827151345324073/882828758644572160/cBM6gLpeRR.mp4)

I feel like I should mention, the TEMP rebuilt in that video is: 00CBB0EDEDADBDF7.TEMP (`scenario_sheep.brick`).

**Comment by musicalmushr00m** [comment]
This issue also causes the Agents in Berlin to talk immediately upon level start. 
TEMP in question is `0077E0D59EFFE1AD.TEMP, scenario_fox.brick`.

**Comment by OrfeasZ** [comment]
Fixed in `2.0.0`.
