### ISSUE TITLE
Parallel conversion in ResourceLib

### ISSUE THREAD

**Issue by atampy25** [OrfeasZ/ZHMTools#37]
While 8535329dbb1dea2f1737884e0449a44f2f669311 apparently added support for converting resources in parallel, there appears to have been a regression since then.

As is, using a semaphore (to control concurrency) with a capacity of greater than one causes a segfault, instantly crashing the process.

**Comment by OrfeasZ** [comment]
Fixed in v3.6.2. You don't have to control concurrency yourself. ResourceLib will now block when its concurrency limit is exceeded.
